<?php
$escape = $this->plugin('escapeHtml');?>

<?php echo $this->pageTitle($this->translate('Exports'), 1, $this->translate('Marc XML Export')); ?>

<a id='page-actions' href="marcxml-export/new">
    <button type="submit"><?php echo $this->translate('New export'); ?></button>
</a>

<?php if(empty($exports)): ?>
    <div><?php echo $this->translate('No exports saved yet');?></div>
<?php else: ?>
<?php echo $this->pagination(); ?>

    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th>
                    <?php echo $this->sortLink($escape($this->translate('Date')), 'id');?>
                </th>
                <th><?php echo $escape($this->translate('Export name'));?></th>
                <th><?php echo $escape($this->translate('Class mapping'));?></th>
                <th><?php echo $escape($this->translate('Resource type'));?></th>
                <th><?php echo $escape($this->translate('Query results'));?></th>
                <th><?php echo $escape($this->translate('Job'));?></th>
                <th><?php echo $escape($this->translate('File'));?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($exports as $export): ?>
                <?php echo $this->ExportDetail($export); ?>
             <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>