<?php
$escapeHtml = $this->plugin('escapeHtml');?>

<?php echo $this->pageTitle($this->translate('Export creation'), 1, $this->translate('Marc XML Export')); ?>

<?php echo $this->form()->openTag($form); ?>
<fieldset id='page-actions'>
    <button type="submit"><?php echo $this->translate('Submit'); ?></button>
</fieldset>
<?php echo $this->formCollection($form, false); ?>

<?php echo $this->form()->closeTag($form); ?>